import "~/styles/globals.css";

import { Inter } from "next/font/google";
// import { AntdRegistry } from "@ant-design/nextjs-registry";
import AntdConfigProvider from "~/context/AntdProvider";

import { Layout, Typography } from "antd";
import { Header } from "antd/lib/layout/layout";
import { Content } from "antd/lib/layout/layout";
import Title from "antd/lib/typography/title";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <Layout>
          <Header
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              backgroundColor: "#fff",
              padding: "12px",
            }}
          >
            {" "}
            <Title level={2}>Hệ thống quản lý sự kiện</Title>
          </Header>
          <Content>
            <AntdConfigProvider>{children}</AntdConfigProvider>
          </Content>
        </Layout>
      </body>
    </html>
  );
}
